name: CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_BACKEND: ${{ secrets.REACT_APP_BACKEND }}
        REACT_APP_NEWSAPI: ${{ secrets.REACT_APP_NEWSAPI }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        BRANCH: gh-pages
        FOLDER: build
